### ISSUE TITLE
Hacking?

### ISSUE THREAD

**Issue by fullofcaffeine** [minutebase/ember-can#21]
Hi!

Does it support integration with, say, CanCanCan (Rails) on the sever, or anything else that can confirm the authorization rule before performing performing the actual action? How to deal with that to avoid someone hacking the javascript app to gain access to other abilities while keeping the rules DRY?

**Comment by blimmer** [comment]
You do not (and should not) have to hardcode who has access in the Javascript.

Your server should include the roles in the user's payload (retrieved on login). [ember-simple-auth](http://ember-simple-auth.com/) is good for maintaining the user session on the client-side. Since a user can muck around with anything on their end, the server should **always** validate that a user has permissions to do something before allowing them to do it.

You can definitely use with can can can, I do.

**Comment by blimmer** [comment]
See also #24
