### ISSUE TITLE
Do I have to hardcode who has access?

### ISSUE THREAD

**Issue by HERRKIN** [minutebase/ember-can#22]
I am thinking of rewriting my php app to full stack js using SANE but we do something there that I dont know how to do with this type of techology, I see here that you define manually who has access  to what in the app. what about if I have a configuration on the app for the profiles? I mean I am admin, I create a profile called canmakesomething, and via the ember app I select what modules it can access, so basically the ember app just needs to ask the server for the access rights of the profile so it can then use the abilities on the client side. Did I make my self clear?  it would be good to configure the abilities from a json file or something like that.

**Comment by blimmer** [comment]
You do not (and should not) hardcode who has access in the Javascript. 

Your server should include the roles in the user's payload (retrieved on login). [ember-simple-auth](http://ember-simple-auth.com/) is good for maintaining the user session on the client-side. Since a user can muck around with anything on their end, the server should **always** validate that a user has permissions to do something before allowing them to do it.

**Comment by blimmer** [comment]
I would also have a look at [this can can port](https://github.com/vdemedes/cancan) for node. Since this is not an issue with this library, I'm going to go ahead and close this thread. If you need more help, I'd suggest [the ember community slack](http://emberjs.com/community/), stack overflow, etc.

**Comment by blimmer** [comment]
See also #24
